// <auto-generated />
using Asignacion.TrabajoFinal.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asignacion.TrabajoFinal.Database.Migraciones
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251231032507_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asignacion.TrabajoFinal.Database.Entities.ProductoEntity", b =>
                {
                    b.Property<int>("CodigoProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoProducto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstatusProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("ExistenciaProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioProducto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodigoProducto");

                    b.ToTable("producto");
                });
#pragma warning restore 612, 618
        }
    }
}
